import type { EraId, ShipDef, ShipKind, UpgradeDef } from './types';
import { ERA_ROSTERS, SAIL_ROSTER } from './rosters';

export const SHIP_DEFS: Record<ShipKind, ShipDef> = {
  player: {
    kind: 'player',
    name: 'The Black Gull',
    faction: 'pirate',
    length: 62,
    width: 22,
    hp: 100,
    speed: 195,
    accel: 105,
    turn: 2.05,
    cannons: 3,
    reload: 1.4,
    damage: 12,
    range: 430,
    ballSpeed: 580,
    masts: 2,
    crew: 45,
    value: 0,
    coins: 0,
    hull: '#3b2314',
    deck: '#a0703f',
    trim: '#9e1f1f',
    sail: '#2b2623',
    sailShade: '#120f0d',
  },
  merchant: {
    kind: 'merchant',
    name: 'Merchant Fluyt',
    trader: true,
    faction: 'merchant',
    length: 58,
    width: 24,
    hp: 40,
    speed: 112,
    accel: 55,
    turn: 1.1,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 320,
    ballSpeed: 430,
    masts: 2,
    crew: 24,
    value: 120,
    coins: 11,
    hull: '#6b4a2b',
    deck: '#b8905c',
    trim: '#2e5e8c',
    sail: '#eadcbc',
    sailShade: '#bba57a',
  },
  // Fast trader. Outruns most warships; catch it on a broad reach.
  schooner: {
    kind: 'schooner',
    name: 'Blockade Runner',
    faction: 'merchant',
    length: 56,
    width: 18,
    hp: 44,
    speed: 182,
    accel: 96,
    turn: 1.6,
    cannons: 1,
    reload: 3,
    damage: 5,
    range: 330,
    ballSpeed: 450,
    masts: 2,
    crew: 20,
    value: 190,
    coins: 13,
    hull: '#5c4326',
    deck: '#c39a62',
    trim: '#2f8f6f',
    sail: '#f7f0dc',
    sailShade: '#cdc09c',
  },
  // Heavy, slow, 2 gun decks (`decks: 2` draws the 2nd port row). Jackpot loot.
  galleon: {
    kind: 'galleon',
    name: 'Treasure Galleon',
    treasure: true,
    faction: 'spain',
    length: 96,
    width: 34,
    hp: 260,
    speed: 104,
    accel: 44,
    turn: 0.82,
    cannons: 3,
    reload: 3.1,
    damage: 8,
    range: 390,
    ballSpeed: 480,
    masts: 3,
    crew: 90,
    value: 900,
    coins: 34,
    hull: '#5b2f16',
    deck: '#c08a46',
    trim: '#e8c14a',
    sail: '#f7ecd2',
    sailShade: '#cfbd92',
    decks: 2,
  },
  sloop: {
    kind: 'sloop',
    name: 'Guarda Costa Sloop',
    faction: 'spain',
    length: 54,
    width: 19,
    hp: 46,
    speed: 168,
    accel: 85,
    turn: 1.55,
    cannons: 2,
    reload: 2.5,
    damage: 7,
    range: 380,
    ballSpeed: 480,
    masts: 1,
    crew: 26,
    value: 150,
    coins: 7,
    hull: '#5a2e1c',
    deck: '#ab7742',
    trim: '#d4a72c',
    sail: '#f4ecd6',
    sailShade: '#cdbd96',
  },
  // Fastest sailing hull in the game; fragile, quick-firing single gun.
  cutter: {
    kind: 'cutter',
    name: 'Revenue Cutter',
    faction: 'england',
    length: 46,
    width: 16,
    hp: 38,
    speed: 205,
    accel: 125,
    turn: 1.95,
    cannons: 1,
    reload: 1.7,
    damage: 5,
    range: 330,
    ballSpeed: 520,
    masts: 1,
    crew: 18,
    value: 170,
    coins: 6,
    hull: '#26303f',
    deck: '#a98a5c',
    trim: '#d8d2c4',
    sail: '#fbf7ec',
    sailShade: '#d2cab4',
  },
  brig: {
    kind: 'brig',
    name: 'Royal Navy Brig',
    faction: 'england',
    length: 70,
    width: 24,
    hp: 95,
    speed: 150,
    accel: 68,
    turn: 1.2,
    cannons: 3,
    reload: 2.3,
    damage: 8,
    range: 400,
    ballSpeed: 500,
    masts: 2,
    crew: 48,
    value: 260,
    coins: 10,
    hull: '#2c2b3b',
    deck: '#9d7d52',
    trim: '#2a57a8',
    sail: '#f6f1e4',
    sailShade: '#cfc6ad',
  },
  // Fast 3-mast raider. Longer reach than the brig, thinner skin.
  corvette: {
    kind: 'corvette',
    name: 'French Corvette',
    faction: 'france',
    length: 72,
    width: 25,
    hp: 120,
    speed: 162,
    accel: 74,
    turn: 1.28,
    cannons: 3,
    reload: 2.0,
    damage: 8,
    range: 415,
    ballSpeed: 515,
    masts: 3,
    crew: 55,
    value: 330,
    coins: 12,
    hull: '#2f3b52',
    deck: '#a8824c',
    trim: '#dfe3ea',
    sail: '#f8f4e8',
    sailShade: '#cfc9b6',
  },
  // `mortar: true` — lobs slow arcing shells instead of flat broadsides.
  // Draws a mortar pit on deck. Keep moving when one is on the field.
  bombketch: {
    kind: 'bombketch',
    name: 'Bomb Ketch',
    faction: 'france',
    length: 62,
    width: 26,
    hp: 105,
    speed: 112,
    accel: 50,
    turn: 0.95,
    cannons: 1,
    reload: 4.4,
    damage: 22,
    range: 560,
    ballSpeed: 250,
    masts: 2,
    crew: 40,
    value: 380,
    coins: 11,
    hull: '#3a3a30',
    deck: '#9c8a5e',
    trim: '#7d5a2c',
    sail: '#efe7d0',
    sailShade: '#c4bb9e',
    mortar: true,
  },
  frigate: {
    kind: 'frigate',
    name: 'Spanish Frigate',
    faction: 'spain',
    length: 84,
    width: 28,
    hp: 170,
    speed: 140,
    accel: 58,
    turn: 1.0,
    cannons: 4,
    reload: 2.4,
    damage: 9,
    range: 430,
    ballSpeed: 520,
    masts: 3,
    crew: 70,
    value: 420,
    coins: 14,
    hull: '#4a2418',
    deck: '#a5773f',
    trim: '#d9b233',
    sail: '#f4ead0',
    sailShade: '#cbb88f',
  },
  // Pirate-hunter. `seesThroughDisguise` — false flags never fool it.
  privateer: {
    kind: 'privateer',
    name: 'Rival Privateer',
    faction: 'pirate',
    length: 66,
    width: 23,
    hp: 130,
    speed: 188,
    accel: 100,
    turn: 1.5,
    cannons: 3,
    reload: 1.85,
    damage: 9,
    range: 420,
    ballSpeed: 540,
    masts: 2,
    crew: 50,
    value: 520,
    coins: 18,
    hull: '#33221b',
    deck: '#8d6236',
    trim: '#b03a2e',
    sail: '#4a423c',
    sailShade: '#241f1c',
    seesThroughDisguise: true,
  },
  manowar: {
    kind: 'manowar',
    name: "Man-o'-War",
    boss: true,
    faction: 'england',
    length: 112,
    width: 36,
    hp: 460,
    speed: 110,
    accel: 42,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 460,
    ballSpeed: 520,
    decks: 2, // two rows of gun ports — she's a ship of the line
    masts: 3,
    crew: 120,
    value: 1200,
    coins: 26,
    hull: '#1f2233',
    deck: '#8f7048',
    trim: '#c9a227',
    sail: '#fbf7ec',
    sailShade: '#d7cfb6',
  },
  fireship: {
    kind: 'fireship',
    name: 'Fire Ship',
    faction: 'fire',
    length: 50,
    width: 18,
    hp: 28,
    speed: 185,
    accel: 115,
    turn: 1.5,
    cannons: 0,
    reload: 99,
    damage: 0,
    range: 0,
    ballSpeed: 0,
    masts: 1,
    crew: 6,
    value: 90,
    coins: 3,
    hull: '#2a1a10',
    deck: '#5b3a22',
    trim: '#ff6a00',
    sail: '#51403a',
    sailShade: '#2a1e18',
    seesThroughDisguise: true,
  },
  // ── SMALL CRAFT · kind='warCanoe' · War Canoe ────────────────────────────
  // Island natives. Paddled, so wind means nothing to them, and unarmed — they
  // close and stab instead of firing. Comes out of the islands in packs.
  warCanoe: {
    kind: 'warCanoe',
    name: 'War Canoe',
    faction: 'native',
    length: 34,
    width: 11,
    hp: 26,
    speed: 172,
    accel: 150,
    turn: 2.3,
    cannons: 0,
    reload: 99,
    damage: 0,
    range: 0,
    ballSpeed: 0,
    masts: 0,
    crew: 12,
    value: 140,
    coins: 9,
    hull: '#6a4a2a',
    deck: '#8d6a3f',
    trim: '#c0392b',
    sail: '#8a6a3a',
    sailShade: '#5a3f20',
    hullStyle: 'canoe',
    oared: true,
    native: true,
  },
  // ── SMALL CRAFT · kind='fishingCanoe' · Fishing Canoe ────────────────────
  // Islanders working the shallows. Unarmed, bolts for cover, worth a few coins.
  fishingCanoe: {
    kind: 'fishingCanoe',
    name: 'Fishing Canoe',
    faction: 'native',
    length: 30,
    width: 12,
    hp: 18,
    speed: 118,
    accel: 110,
    turn: 2.0,
    cannons: 0,
    reload: 99,
    damage: 0,
    range: 0,
    ballSpeed: 0,
    masts: 0,
    crew: 5,
    value: 70,
    coins: 16,
    hull: '#7d5c34',
    deck: '#a37f4c',
    trim: '#3f7f6a',
    sail: '#9a7a44',
    sailShade: '#6b5230',
    hullStyle: 'canoe',
    oared: true,
    native: true,
  },
  // ── SMALL CRAFT · kind='rowboat' · Ship's Rowboat ────────────────────────
  // Crew escaping a sinking hull, or a tender running errands. Oared, unarmed,
  // and it usually carries something worth having.
  rowboat: {
    kind: 'rowboat',
    name: "Ship's Rowboat",
    faction: 'merchant',
    length: 26,
    width: 10,
    hp: 14,
    speed: 128,
    accel: 120,
    turn: 2.4,
    cannons: 0,
    reload: 99,
    damage: 0,
    range: 0,
    ballSpeed: 0,
    masts: 0,
    crew: 6,
    value: 90,
    coins: 12,
    hull: '#5c4326',
    deck: '#9d7a4a',
    trim: '#c9a227',
    sail: '#7a5c34',
    sailShade: '#523c20',
    oared: true,
  },
  // ── AGE OF SAIL · new late-pool ships ──
  xebec: {
    kind: 'xebec',
    name: 'Barbary Xebec',
    faction: 'pirate',
    length: 58,
    width: 19,
    hp: 55,
    speed: 196,
    accel: 110,
    turn: 1.7,
    cannons: 2,
    reload: 2.1,
    damage: 7,
    range: 370,
    ballSpeed: 500,
    masts: 2,
    value: 240,
    coins: 9,
    crew: 38,
    hull: '#4a3218',
    deck: '#a0703f',
    trim: '#b5352c',
    sail: '#efe3c4',
    sailShade: '#c3b48c',
    hullStyle: 'dhow',
  },
  lugger: {
    kind: 'lugger',
    name: "Smuggler's Lugger",
    faction: 'france',
    length: 48,
    width: 17,
    hp: 40,
    speed: 192,
    accel: 115,
    turn: 1.85,
    cannons: 1,
    reload: 2.2,
    damage: 6,
    range: 350,
    ballSpeed: 500,
    masts: 2,
    value: 200,
    coins: 8,
    crew: 26,
    hull: '#3a3a30',
    deck: '#9c8a5e',
    trim: '#7d5a2c',
    sail: '#efe7d0',
    sailShade: '#c4bb9e',
  },
  gunboat: {
    kind: 'gunboat',
    name: 'Spanish Gunboat',
    faction: 'spain',
    length: 42,
    width: 16,
    hp: 34,
    speed: 150,
    accel: 90,
    turn: 1.6,
    cannons: 1,
    reload: 3.0,
    damage: 14,
    range: 380,
    ballSpeed: 500,
    masts: 1,
    value: 130,
    coins: 5,
    crew: 22,
    hull: '#5a2e1c',
    deck: '#ab7742',
    trim: '#d4a72c',
    sail: '#f4ecd6',
    sailShade: '#cdbd96',
  },
  // ── ROME · Carthage must be destroyed ──
  carthGalley: {
    kind: 'carthGalley',
    name: 'Carthaginian Galley',
    faction: 'carthage',
    length: 68,
    width: 20,
    hp: 100,
    speed: 165,
    accel: 95,
    turn: 1.35,
    cannons: 3,
    reload: 2.4,
    damage: 8,
    range: 390,
    ballSpeed: 500,
    masts: 1,
    value: 300,
    coins: 11,
    crew: 70,
    hull: '#4a2430',
    deck: '#a5773f',
    trim: '#c9a227',
    sail: '#e8dcc0',
    sailShade: '#b8a880',
    hullStyle: 'trireme',
    oared: true,
  },
  carthTrader: {
    kind: 'carthTrader',
    name: 'Carthaginian Round Ship',
    faction: 'carthage',
    length: 60,
    width: 26,
    hp: 44,
    speed: 108,
    accel: 52,
    turn: 1.05,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 310,
    ballSpeed: 420,
    masts: 2,
    value: 130,
    coins: 12,
    crew: 22,
    hull: '#6b4a2b',
    deck: '#b8905c',
    trim: '#7a2d5a',
    sail: '#e8dcc0',
    sailShade: '#b8a880',
    trader: true,
    treasure: true,
  },
  carthSeven: {
    kind: 'carthSeven',
    name: "Carthaginian 'Seven'",
    faction: 'carthage',
    length: 104,
    width: 32,
    hp: 430,
    speed: 108,
    accel: 40,
    turn: 0.72,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 510,
    decks: 2,
    masts: 1,
    value: 1150,
    coins: 24,
    crew: 200,
    hull: '#3a1a24',
    deck: '#8f7048',
    trim: '#c9a227',
    sail: '#c9403b',
    sailShade: '#8a2a26',
    hullStyle: 'trireme',
    oared: true,
    boss: true,
  },
  cilician: {
    kind: 'cilician',
    name: 'Cilician Pirate Lembus',
    faction: 'pirate',
    length: 52,
    width: 16,
    hp: 40,
    speed: 195,
    accel: 120,
    turn: 1.9,
    cannons: 2,
    reload: 2.0,
    damage: 6,
    range: 350,
    ballSpeed: 500,
    masts: 1,
    value: 220,
    coins: 9,
    crew: 40,
    hull: '#3a2a1a',
    deck: '#8d6236',
    trim: '#b03a2e',
    sail: '#4a423c',
    sailShade: '#241f1c',
    hullStyle: 'trireme',
    oared: true,
  },
  // ── GREECE · against the Great King ──
  phoenTrireme: {
    kind: 'phoenTrireme',
    name: 'Phoenician Trireme',
    faction: 'persia',
    length: 68,
    width: 20,
    hp: 95,
    speed: 170,
    accel: 95,
    turn: 1.35,
    cannons: 3,
    reload: 2.4,
    damage: 8,
    range: 390,
    ballSpeed: 500,
    masts: 1,
    value: 290,
    coins: 11,
    crew: 65,
    hull: '#5a3030',
    deck: '#a5773f',
    trim: '#2e5e8c',
    sail: '#efe3c4',
    sailShade: '#c3b48c',
    hullStyle: 'trireme',
    oared: true,
  },
  persTransport: {
    kind: 'persTransport',
    name: 'Persian Horse Transport',
    faction: 'persia',
    length: 60,
    width: 26,
    hp: 44,
    speed: 105,
    accel: 52,
    turn: 1.05,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 310,
    ballSpeed: 420,
    masts: 2,
    value: 130,
    coins: 12,
    crew: 24,
    hull: '#6b4a2b',
    deck: '#b8905c',
    trim: '#b3261e',
    sail: '#e8dcc0',
    sailShade: '#b8a880',
    trader: true,
    treasure: true,
  },
  ionianGalley: {
    kind: 'ionianGalley',
    name: 'Ionian Rebel Galley',
    faction: 'persia',
    length: 60,
    width: 17,
    hp: 50,
    speed: 190,
    accel: 120,
    turn: 1.8,
    cannons: 2,
    reload: 2.1,
    damage: 6,
    range: 360,
    ballSpeed: 500,
    masts: 1,
    value: 230,
    coins: 9,
    crew: 45,
    hull: '#3a4a6b',
    deck: '#a88a5a',
    trim: '#d9d2c0',
    sail: '#e8e0cc',
    sailShade: '#b8ac88',
    hullStyle: 'trireme',
    oared: true,
  },
  sidonianRoyal: {
    kind: 'sidonianRoyal',
    name: 'Sidonian Royal Galley',
    faction: 'persia',
    length: 100,
    width: 30,
    hp: 420,
    speed: 110,
    accel: 42,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 510,
    decks: 2,
    masts: 1,
    value: 1150,
    coins: 24,
    crew: 190,
    hull: '#4a1a2a',
    deck: '#8f7048',
    trim: '#e8c14a',
    sail: '#c9403b',
    sailShade: '#8a2a26',
    hullStyle: 'trireme',
    oared: true,
    boss: true,
  },
  // ── ARABIA · monsoon raiders ──
  warDhow: {
    kind: 'warDhow',
    name: 'Omani War Dhow',
    faction: 'arab',
    length: 64,
    width: 22,
    hp: 95,
    speed: 165,
    accel: 85,
    turn: 1.3,
    cannons: 3,
    reload: 2.3,
    damage: 8,
    range: 400,
    ballSpeed: 500,
    masts: 1,
    value: 280,
    coins: 10,
    crew: 45,
    hull: '#5c4326',
    deck: '#c39a62',
    trim: '#2e8a8a',
    sail: '#f0e6d0',
    sailShade: '#c0b090',
    hullStyle: 'dhow',
  },
  ghurab: {
    kind: 'ghurab',
    name: 'Qasimi Ghurab',
    faction: 'arab',
    length: 50,
    width: 17,
    hp: 42,
    speed: 198,
    accel: 115,
    turn: 1.8,
    cannons: 2,
    reload: 2.1,
    damage: 6,
    range: 360,
    ballSpeed: 500,
    masts: 1,
    value: 230,
    coins: 8,
    crew: 30,
    hull: '#4a3620',
    deck: '#a8824c',
    trim: '#c9403b',
    sail: '#f0e6d0',
    sailShade: '#c0b090',
    hullStyle: 'dhow',
  },
  baghlah: {
    kind: 'baghlah',
    name: 'Gulf Baghlah',
    faction: 'arab',
    length: 72,
    width: 28,
    hp: 120,
    speed: 125,
    accel: 55,
    turn: 1.0,
    cannons: 2,
    reload: 2.8,
    damage: 7,
    range: 360,
    ballSpeed: 480,
    masts: 2,
    value: 420,
    coins: 16,
    crew: 50,
    hull: '#6b4a2b',
    deck: '#c09a62',
    trim: '#2e5e8c',
    sail: '#efe3c4',
    sailShade: '#c3b48c',
    hullStyle: 'dhow',
    trader: true,
    treasure: true,
  },
  sultanFlagship: {
    kind: 'sultanFlagship',
    name: "Sultan's Flagship Ghanja",
    faction: 'arab',
    length: 100,
    width: 34,
    hp: 440,
    speed: 115,
    accel: 42,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 510,
    decks: 2,
    masts: 2,
    value: 1150,
    coins: 24,
    crew: 150,
    hull: '#3a2a4a',
    deck: '#8f7048',
    trim: '#c9a227',
    sail: '#f0e6d0',
    sailShade: '#c0b090',
    hullStyle: 'dhow',
    boss: true,
  },
  // ── CHINA · East China Sea ──
  warlordJunk: {
    kind: 'warlordJunk',
    name: 'Warlord Battle Junk',
    faction: 'china',
    length: 74,
    width: 28,
    hp: 130,
    speed: 145,
    accel: 60,
    turn: 1.05,
    cannons: 3,
    reload: 2.4,
    damage: 9,
    range: 410,
    ballSpeed: 510,
    masts: 3,
    value: 320,
    coins: 12,
    crew: 65,
    hull: '#4a2c1a',
    deck: '#9a7a4a',
    trim: '#c9403b',
    sail: '#b89a5e',
    sailShade: '#8a6f3f',
    hullStyle: 'junk',
  },
  wokouJunk: {
    kind: 'wokouJunk',
    name: 'Wokou Raider Junk',
    faction: 'japan',
    length: 60,
    width: 22,
    hp: 60,
    speed: 185,
    accel: 100,
    turn: 1.5,
    cannons: 2,
    reload: 2.2,
    damage: 7,
    range: 370,
    ballSpeed: 500,
    masts: 2,
    value: 260,
    coins: 10,
    crew: 45,
    hull: '#3a3430',
    deck: '#8a7a5a',
    trim: '#b5352c',
    sail: '#a8905a',
    sailShade: '#78643c',
    hullStyle: 'junk',
  },
  grainJunk: {
    kind: 'grainJunk',
    name: 'Tribute Grain Junk',
    faction: 'china',
    length: 70,
    width: 30,
    hp: 60,
    speed: 115,
    accel: 55,
    turn: 1.0,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 320,
    ballSpeed: 430,
    masts: 3,
    value: 200,
    coins: 14,
    crew: 30,
    hull: '#5a3a20',
    deck: '#9a7a4a',
    trim: '#c9a227',
    sail: '#c0a062',
    sailShade: '#907848',
    hullStyle: 'junk',
    trader: true,
    treasure: true,
  },
  pirateKing: {
    kind: 'pirateKing',
    name: 'Red Flag Pirate King',
    faction: 'pirate',
    length: 104,
    width: 36,
    hp: 450,
    speed: 112,
    accel: 42,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 510,
    decks: 2,
    masts: 3,
    value: 1200,
    coins: 26,
    crew: 160,
    hull: '#2a1a10',
    deck: '#5b3a22',
    trim: '#ff6a00',
    sail: '#8a7448',
    sailShade: '#5c4c2e',
    hullStyle: 'junk',
    boss: true,
  },
  // ── JAPAN · Sengoku waters ──
  sekiBune: {
    kind: 'sekiBune',
    name: 'Seki-bune Warship',
    faction: 'japan',
    length: 62,
    width: 22,
    hp: 85,
    speed: 160,
    accel: 80,
    turn: 1.3,
    cannons: 3,
    reload: 2.3,
    damage: 8,
    range: 400,
    ballSpeed: 500,
    masts: 1,
    value: 280,
    coins: 10,
    crew: 50,
    hull: '#3a3434',
    deck: '#8a7a5a',
    trim: '#c9403b',
    sail: '#e8e0cc',
    sailShade: '#b0a488',
  },
  kobaya: {
    kind: 'kobaya',
    name: 'Kobaya Scout Boat',
    faction: 'japan',
    length: 44,
    width: 15,
    hp: 36,
    speed: 200,
    accel: 120,
    turn: 1.9,
    cannons: 1,
    reload: 2.0,
    damage: 6,
    range: 340,
    ballSpeed: 500,
    masts: 1,
    value: 200,
    coins: 7,
    crew: 25,
    hull: '#3a3434',
    deck: '#8a7a5a',
    trim: '#2e5e8c',
    sail: '#e8e0cc',
    sailShade: '#b0a488',
  },
  riceBune: {
    kind: 'riceBune',
    name: 'Rice-laden Bune',
    faction: 'japan',
    length: 60,
    width: 26,
    hp: 50,
    speed: 115,
    accel: 55,
    turn: 1.1,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 320,
    ballSpeed: 430,
    masts: 1,
    value: 170,
    coins: 13,
    crew: 28,
    hull: '#5a4a30',
    deck: '#9a8a62',
    trim: '#7a8a3a',
    sail: '#e0d4b8',
    sailShade: '#b0a488',
    trader: true,
    treasure: true,
  },
  moriFlagship: {
    kind: 'moriFlagship',
    name: 'Mōri Atakebune Flagship',
    faction: 'japan',
    length: 100,
    width: 34,
    hp: 450,
    speed: 112,
    accel: 42,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 520,
    decks: 2,
    masts: 1,
    value: 1180,
    coins: 25,
    crew: 170,
    hull: '#24242c',
    deck: '#8a7a5a',
    trim: '#c9a227',
    sail: '#e8e0cc',
    sailShade: '#b0a488',
    hullStyle: 'atakebune',
    boss: true,
  },
  // ── MĀORI · Musket Wars ──
  rivalWaka: {
    kind: 'rivalWaka',
    name: 'Rival Iwi Waka Taua',
    faction: 'maori',
    length: 56,
    width: 15,
    hp: 70,
    speed: 180,
    accel: 140,
    turn: 2.1,
    cannons: 2,
    reload: 2.2,
    damage: 6,
    range: 340,
    ballSpeed: 480,
    masts: 0,
    value: 240,
    coins: 10,
    crew: 45,
    hull: '#4a2e18',
    deck: '#7a5a34',
    trim: '#b5352c',
    sail: '#9a7a44',
    sailShade: '#6b5230',
    hullStyle: 'canoe',
    oared: true,
  },
  arikiWaka: {
    kind: 'arikiWaka',
    name: 'Ariki Great Waka',
    faction: 'maori',
    length: 84,
    width: 20,
    hp: 380,
    speed: 150,
    accel: 90,
    turn: 1.4,
    cannons: 4,
    reload: 2.6,
    damage: 7,
    range: 400,
    ballSpeed: 500,
    masts: 0,
    value: 1100,
    coins: 22,
    crew: 120,
    hull: '#3a2412',
    deck: '#6b4a28',
    trim: '#c9a227',
    sail: '#9a7a44',
    sailShade: '#6b5230',
    hullStyle: 'canoe',
    oared: true,
    boss: true,
  },
  flaxTrader: {
    kind: 'flaxTrader',
    name: 'Flax & Musket Trader',
    faction: 'merchant',
    length: 56,
    width: 22,
    hp: 42,
    speed: 115,
    accel: 60,
    turn: 1.2,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 320,
    ballSpeed: 430,
    masts: 2,
    value: 140,
    coins: 12,
    crew: 20,
    hull: '#5c4326',
    deck: '#c39a62',
    trim: '#3f7f6a',
    sail: '#f7f0dc',
    sailShade: '#cdc09c',
    trader: true,
    treasure: true,
  },
  // ── HAWAIʻI · Unification Wars ──
  rivalWaa: {
    kind: 'rivalWaa',
    name: 'Rival Moku Waʻa Kaua',
    faction: 'hawaii',
    length: 54,
    width: 15,
    hp: 68,
    speed: 185,
    accel: 145,
    turn: 2.2,
    cannons: 2,
    reload: 2.2,
    damage: 6,
    range: 340,
    ballSpeed: 480,
    masts: 0,
    value: 240,
    coins: 10,
    crew: 44,
    hull: '#5a3a20',
    deck: '#7a5a34',
    trim: '#c9a227',
    sail: '#a08050',
    sailShade: '#6f5836',
    hullStyle: 'canoe',
    oared: true,
  },
  kauaiFlagship: {
    kind: 'kauaiFlagship',
    name: 'Kauaʻi Royal Canoe Fleet',
    faction: 'hawaii',
    length: 82,
    width: 20,
    hp: 380,
    speed: 152,
    accel: 90,
    turn: 1.4,
    cannons: 4,
    reload: 2.6,
    damage: 7,
    range: 400,
    ballSpeed: 500,
    masts: 0,
    value: 1100,
    coins: 22,
    crew: 118,
    hull: '#4a2e16',
    deck: '#6b4a28',
    trim: '#b5352c',
    sail: '#a08050',
    sailShade: '#6f5836',
    hullStyle: 'canoe',
    oared: true,
    boss: true,
  },
  sandTrader: {
    kind: 'sandTrader',
    name: 'Sandalwood Trader',
    faction: 'merchant',
    length: 56,
    width: 22,
    hp: 42,
    speed: 115,
    accel: 60,
    turn: 1.2,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 320,
    ballSpeed: 430,
    masts: 2,
    value: 140,
    coins: 12,
    crew: 20,
    hull: '#5c4326',
    deck: '#c39a62',
    trim: '#8a5a2e',
    sail: '#f7f0dc',
    sailShade: '#cdc09c',
    trader: true,
    treasure: true,
  },
  // ── MACEDON · the Besieger's war ──
  rhodesTrieres: {
    kind: 'rhodesTrieres',
    name: 'Rhodian Trieres',
    faction: 'rhodes',
    length: 58,
    width: 16,
    hp: 45,
    speed: 198,
    accel: 125,
    turn: 1.9,
    cannons: 2,
    reload: 2.0,
    damage: 6,
    range: 360,
    ballSpeed: 500,
    masts: 1,
    value: 240,
    coins: 9,
    crew: 45,
    hull: '#4a5a7a',
    deck: '#a88a5a',
    trim: '#d9d2c0',
    sail: '#e8e0cc',
    sailShade: '#b8ac88',
    hullStyle: 'trireme',
    oared: true,
  },
  ptolemGalley: {
    kind: 'ptolemGalley',
    name: 'Ptolemaic Quadrireme',
    faction: 'ptolemy',
    length: 70,
    width: 21,
    hp: 100,
    speed: 165,
    accel: 95,
    turn: 1.35,
    cannons: 3,
    reload: 2.4,
    damage: 8,
    range: 390,
    ballSpeed: 500,
    masts: 1,
    value: 300,
    coins: 11,
    crew: 70,
    hull: '#3a2a5a',
    deck: '#a5773f',
    trim: '#c9a227',
    sail: '#efe3c4',
    sailShade: '#c3b48c',
    hullStyle: 'trireme',
    oared: true,
  },
  alexGrain: {
    kind: 'alexGrain',
    name: 'Alexandrian Grain Ship',
    faction: 'ptolemy',
    length: 62,
    width: 27,
    hp: 46,
    speed: 105,
    accel: 52,
    turn: 1.05,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 310,
    ballSpeed: 420,
    masts: 2,
    value: 135,
    coins: 13,
    crew: 24,
    hull: '#6b4a2b',
    deck: '#b8905c',
    trim: '#3a2a5a',
    sail: '#e8dcc0',
    sailShade: '#b8a880',
    trader: true,
    treasure: true,
  },
  ptolemFlagship: {
    kind: 'ptolemFlagship',
    name: "Ptolemy's Flagship",
    faction: 'ptolemy',
    length: 102,
    width: 31,
    hp: 440,
    speed: 110,
    accel: 42,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 510,
    decks: 2,
    masts: 1,
    value: 1150,
    coins: 24,
    crew: 195,
    hull: '#2a1a4a',
    deck: '#8f7048',
    trim: '#c9a227',
    sail: '#7a2d5a',
    sailShade: '#4a1a36',
    hullStyle: 'trireme',
    oared: true,
    boss: true,
  },
  // ── MAYA · First Contact ──
  mayaRival: {
    kind: 'mayaRival',
    name: 'Rival Ahau War Canoe',
    faction: 'maya',
    length: 56,
    width: 15,
    hp: 70,
    speed: 180,
    accel: 140,
    turn: 2.1,
    cannons: 2,
    reload: 2.2,
    damage: 6,
    range: 340,
    ballSpeed: 480,
    masts: 0,
    value: 240,
    coins: 10,
    crew: 45,
    hull: '#4a3a20',
    deck: '#7a5a34',
    trim: '#2e8a6a',
    sail: '#9a7a44',
    sailShade: '#6b5230',
    hullStyle: 'canoe',
    oared: true,
  },
  cacaoTrader: {
    kind: 'cacaoTrader',
    name: 'Cacao Trading Canoe',
    faction: 'maya',
    length: 58,
    width: 17,
    hp: 44,
    speed: 115,
    accel: 70,
    turn: 1.3,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 310,
    ballSpeed: 430,
    masts: 0,
    value: 140,
    coins: 13,
    crew: 22,
    hull: '#5a4426',
    deck: '#8a6a40',
    trim: '#b5352c',
    sail: '#9a7a44',
    sailShade: '#6b5230',
    hullStyle: 'canoe',
    oared: true,
    trader: true,
    treasure: true,
  },
  conqCaravel: {
    kind: 'conqCaravel',
    name: 'Spanish Caravel',
    faction: 'spain',
    length: 62,
    width: 22,
    hp: 110,
    speed: 150,
    accel: 70,
    turn: 1.2,
    cannons: 3,
    reload: 2.4,
    damage: 8,
    range: 400,
    ballSpeed: 500,
    masts: 2,
    value: 320,
    coins: 12,
    crew: 55,
    hull: '#5a2e1c',
    deck: '#ab7742',
    trim: '#d4a72c',
    sail: '#f4ecd6',
    sailShade: '#cdbd96',
  },
  conqCapitana: {
    kind: 'conqCapitana',
    name: 'Spanish Capitana',
    faction: 'spain',
    length: 100,
    width: 33,
    hp: 420,
    speed: 112,
    accel: 44,
    turn: 0.76,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 510,
    decks: 2,
    masts: 3,
    value: 1150,
    coins: 24,
    crew: 170,
    hull: '#4a2418',
    deck: '#8f7048',
    trim: '#d4a72c',
    sail: '#f4ecd6',
    sailShade: '#cdbd96',
    boss: true,
  },
  // ── INCA · Pacific balsas ──
  rivalBalsa: {
    kind: 'rivalBalsa',
    name: 'Rival Chincha Balsa',
    faction: 'inca',
    length: 64,
    width: 24,
    hp: 105,
    speed: 150,
    accel: 80,
    turn: 1.3,
    cannons: 3,
    reload: 2.4,
    damage: 8,
    range: 380,
    ballSpeed: 490,
    masts: 0,
    value: 300,
    coins: 11,
    crew: 55,
    hull: '#6b5230',
    deck: '#8a6a40',
    trim: '#b5352c',
    sail: '#c0a062',
    sailShade: '#907848',
    hullStyle: 'canoe',
    oared: true,
  },
  punaBalsa: {
    kind: 'punaBalsa',
    name: 'Puná War Balsa',
    faction: 'puna',
    length: 58,
    width: 22,
    hp: 75,
    speed: 175,
    accel: 135,
    turn: 2.0,
    cannons: 2,
    reload: 2.2,
    damage: 6,
    range: 340,
    ballSpeed: 480,
    masts: 0,
    value: 240,
    coins: 10,
    crew: 46,
    hull: '#5a4a28',
    deck: '#7a5a34',
    trim: '#2e5e8c',
    sail: '#a08050',
    sailShade: '#6f5836',
    hullStyle: 'canoe',
    oared: true,
  },
  spondylusTrader: {
    kind: 'spondylusTrader',
    name: 'Spondylus Trading Balsa',
    faction: 'inca',
    length: 60,
    width: 23,
    hp: 44,
    speed: 112,
    accel: 65,
    turn: 1.25,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 310,
    ballSpeed: 430,
    masts: 0,
    value: 140,
    coins: 13,
    crew: 22,
    hull: '#6b5230',
    deck: '#8a6a40',
    trim: '#c94a6a',
    sail: '#c0a062',
    sailShade: '#907848',
    hullStyle: 'canoe',
    oared: true,
    trader: true,
    treasure: true,
  },
  punaArmada: {
    kind: 'punaArmada',
    name: 'Puná Island Armada',
    faction: 'puna',
    length: 84,
    width: 28,
    hp: 400,
    speed: 150,
    accel: 85,
    turn: 1.35,
    cannons: 4,
    reload: 2.6,
    damage: 7,
    range: 400,
    ballSpeed: 500,
    masts: 0,
    value: 1100,
    coins: 22,
    crew: 120,
    hull: '#4a3a22',
    deck: '#6b4a28',
    trim: '#c9a227',
    sail: '#a08050',
    sailShade: '#6f5836',
    hullStyle: 'canoe',
    oared: true,
    boss: true,
  },
  // ── LEPANTO · galleys of the Holy League ──
  venetianGalley: {
    kind: 'venetianGalley',
    name: 'Venetian War Galley',
    faction: 'venice',
    length: 70,
    width: 20,
    hp: 100,
    speed: 168,
    accel: 95,
    turn: 1.35,
    cannons: 3,
    reload: 2.4,
    damage: 8,
    range: 390,
    ballSpeed: 500,
    masts: 1,
    value: 300,
    coins: 11,
    crew: 70,
    hull: '#5a2e1c',
    deck: '#a5773f',
    trim: '#c9a227',
    sail: '#efe3c4',
    sailShade: '#c3b48c',
    hullStyle: 'trireme',
    oared: true,
  },
  spanishGalley: {
    kind: 'spanishGalley',
    name: 'Spanish Tercios Galley',
    faction: 'spain',
    length: 72,
    width: 21,
    hp: 115,
    speed: 160,
    accel: 90,
    turn: 1.3,
    cannons: 3,
    reload: 2.5,
    damage: 9,
    range: 400,
    ballSpeed: 510,
    masts: 1,
    value: 330,
    coins: 12,
    crew: 75,
    hull: '#4a2418',
    deck: '#8f7048',
    trim: '#d4a72c',
    sail: '#f4ecd6',
    sailShade: '#cdbd96',
    hullStyle: 'trireme',
    oared: true,
  },
  venetianTrader: {
    kind: 'venetianTrader',
    name: 'Venetian Merchant Galley',
    faction: 'venice',
    length: 64,
    width: 26,
    hp: 48,
    speed: 110,
    accel: 55,
    turn: 1.05,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 310,
    ballSpeed: 430,
    masts: 2,
    value: 140,
    coins: 13,
    crew: 26,
    hull: '#6b4a2b',
    deck: '#b8905c',
    trim: '#b3261e',
    sail: '#efe3c4',
    sailShade: '#c3b48c',
    oared: true,
    trader: true,
    treasure: true,
  },
  laReal: {
    kind: 'laReal',
    name: "Don Juan's La Real",
    faction: 'spain',
    length: 104,
    width: 30,
    hp: 450,
    speed: 112,
    accel: 44,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 520,
    decks: 2,
    masts: 2,
    value: 1180,
    coins: 25,
    crew: 180,
    hull: '#3a1a12',
    deck: '#8f7048',
    trim: '#e8c14a',
    sail: '#c9403b',
    sailShade: '#8a2a26',
    hullStyle: 'trireme',
    oared: true,
    boss: true,
  },
  // ── IMJIN WAR · Hideyoshi's flagship ──
  japanFlagship: {
    kind: 'japanFlagship',
    name: 'Samurai Flagship Atakebune',
    faction: 'japan',
    length: 100,
    width: 34,
    hp: 450,
    speed: 112,
    accel: 42,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 520,
    decks: 2,
    masts: 1,
    value: 1180,
    coins: 25,
    crew: 170,
    hull: '#24242c',
    deck: '#8a7a5a',
    trim: '#b5352c',
    sail: '#e8e0cc',
    sailShade: '#b0a488',
    hullStyle: 'atakebune',
    boss: true,
  },
  // ── CONSTANTINOPLE · the Caliph's galleys ──
  umayyadGalley: {
    kind: 'umayyadGalley',
    name: 'Umayyad War Galley',
    faction: 'arab',
    length: 68,
    width: 20,
    hp: 95,
    speed: 168,
    accel: 95,
    turn: 1.35,
    cannons: 3,
    reload: 2.4,
    damage: 8,
    range: 390,
    ballSpeed: 500,
    masts: 1,
    value: 290,
    coins: 11,
    crew: 65,
    hull: '#4a3620',
    deck: '#a5773f',
    trim: '#2e8a8a',
    sail: '#efe3c4',
    sailShade: '#c3b48c',
    hullStyle: 'trireme',
    oared: true,
  },
  shalandi: {
    kind: 'shalandi',
    name: 'Shalandi Scout',
    faction: 'arab',
    length: 52,
    width: 16,
    hp: 40,
    speed: 198,
    accel: 125,
    turn: 1.9,
    cannons: 2,
    reload: 2.0,
    damage: 6,
    range: 350,
    ballSpeed: 500,
    masts: 1,
    value: 230,
    coins: 8,
    crew: 40,
    hull: '#3a2a1a',
    deck: '#8d6236',
    trim: '#c9403b',
    sail: '#e8dcc0',
    sailShade: '#b8a880',
    hullStyle: 'trireme',
    oared: true,
  },
  umayyadSupply: {
    kind: 'umayyadSupply',
    name: 'Umayyad Supply Ship',
    faction: 'arab',
    length: 60,
    width: 26,
    hp: 46,
    speed: 108,
    accel: 52,
    turn: 1.05,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 310,
    ballSpeed: 420,
    masts: 2,
    value: 135,
    coins: 13,
    crew: 24,
    hull: '#6b4a2b',
    deck: '#b8905c',
    trim: '#0f6f6a',
    sail: '#e8dcc0',
    sailShade: '#b8a880',
    trader: true,
    treasure: true,
  },
  maslamaFlagship: {
    kind: 'maslamaFlagship',
    name: "Maslama's Flagship",
    faction: 'arab',
    length: 102,
    width: 30,
    hp: 440,
    speed: 110,
    accel: 42,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 510,
    decks: 2,
    masts: 1,
    value: 1150,
    coins: 24,
    crew: 190,
    hull: '#2a1a2a',
    deck: '#8f7048',
    trim: '#c9a227',
    sail: '#7a2d5a',
    sailShade: '#4a1a36',
    hullStyle: 'trireme',
    oared: true,
    boss: true,
  },
  // ── SEA PEOPLES · Sherden raiders ──
  sherdenGalley: {
    kind: 'sherdenGalley',
    name: 'Sherden War Galley',
    faction: 'sherden',
    length: 66,
    width: 19,
    hp: 95,
    speed: 170,
    accel: 100,
    turn: 1.4,
    cannons: 3,
    reload: 2.4,
    damage: 8,
    range: 380,
    ballSpeed: 500,
    masts: 1,
    value: 290,
    coins: 11,
    crew: 60,
    hull: '#4a4038',
    deck: '#8a7a5a',
    trim: '#c0c0c0',
    sail: '#d8d0b8',
    sailShade: '#a89e80',
    hullStyle: 'trireme',
    oared: true,
  },
  sherdenRaider: {
    kind: 'sherdenRaider',
    name: 'Sherden Raider',
    faction: 'sherden',
    length: 52,
    width: 15,
    hp: 42,
    speed: 198,
    accel: 130,
    turn: 1.95,
    cannons: 2,
    reload: 2.0,
    damage: 6,
    range: 350,
    ballSpeed: 500,
    masts: 1,
    value: 230,
    coins: 8,
    crew: 38,
    hull: '#3a3430',
    deck: '#7a6a4a',
    trim: '#8a8a8a',
    sail: '#cfc6ae',
    sailShade: '#9e9478',
    hullStyle: 'trireme',
    oared: true,
  },
  clanShip: {
    kind: 'clanShip',
    name: 'Sea Peoples Clan Ship',
    faction: 'sherden',
    length: 62,
    width: 26,
    hp: 46,
    speed: 105,
    accel: 50,
    turn: 1.0,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 300,
    ballSpeed: 420,
    masts: 1,
    value: 135,
    coins: 13,
    crew: 26,
    hull: '#5a4a34',
    deck: '#9a8a62',
    trim: '#7a5a3a',
    sail: '#d8d0b8',
    sailShade: '#a89e80',
    trader: true,
    treasure: true,
  },
  sherdenArmada: {
    kind: 'sherdenArmada',
    name: 'Great Sherden Armada',
    faction: 'sherden',
    length: 100,
    width: 30,
    hp: 430,
    speed: 112,
    accel: 44,
    turn: 0.76,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 440,
    ballSpeed: 510,
    decks: 2,
    masts: 1,
    value: 1150,
    coins: 24,
    crew: 185,
    hull: '#2a2624',
    deck: '#7a6a4a',
    trim: '#c9a227',
    sail: '#8a2a26',
    sailShade: '#5a1a18',
    hullStyle: 'trireme',
    oared: true,
    boss: true,
  },
  // ── BAY OF BENGAL · Srivijayan jongs ──
  srivJong: {
    kind: 'srivJong',
    name: 'Srivijayan War Jong',
    faction: 'srivijaya',
    length: 76,
    width: 29,
    hp: 130,
    speed: 145,
    accel: 60,
    turn: 1.05,
    cannons: 3,
    reload: 2.4,
    damage: 9,
    range: 410,
    ballSpeed: 510,
    masts: 3,
    value: 320,
    coins: 12,
    crew: 65,
    hull: '#4a2e1a',
    deck: '#9a7a4a',
    trim: '#2e8a6a',
    sail: '#c9a86a',
    sailShade: '#9a7c4c',
    hullStyle: 'junk',
  },
  srivScout: {
    kind: 'srivScout',
    name: 'Orang Laut Scout Prahu',
    faction: 'srivijaya',
    length: 48,
    width: 16,
    hp: 38,
    speed: 200,
    accel: 120,
    turn: 1.9,
    cannons: 1,
    reload: 2.0,
    damage: 6,
    range: 340,
    ballSpeed: 500,
    masts: 1,
    value: 210,
    coins: 8,
    crew: 25,
    hull: '#3a2c1a',
    deck: '#8a6a40',
    trim: '#c9a227',
    sail: '#d8cca8',
    sailShade: '#a89878',
  },
  spiceTrader: {
    kind: 'spiceTrader',
    name: 'Spice Jong',
    faction: 'srivijaya',
    length: 72,
    width: 30,
    hp: 60,
    speed: 112,
    accel: 55,
    turn: 1.0,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 320,
    ballSpeed: 430,
    masts: 3,
    value: 200,
    coins: 14,
    crew: 30,
    hull: '#5a3a20',
    deck: '#9a7a4a',
    trim: '#c9a227',
    sail: '#c9a86a',
    sailShade: '#9a7c4c',
    hullStyle: 'junk',
    trader: true,
    treasure: true,
  },
  royalJong: {
    kind: 'royalJong',
    name: 'Srivijayan Royal Jong',
    faction: 'srivijaya',
    length: 104,
    width: 36,
    hp: 450,
    speed: 112,
    accel: 42,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 510,
    decks: 2,
    masts: 3,
    value: 1180,
    coins: 25,
    crew: 165,
    hull: '#2a1a10',
    deck: '#5b3a22',
    trim: '#e8c14a',
    sail: '#a8905a',
    sailShade: '#78643c',
    hullStyle: 'junk',
    boss: true,
  },
  // ── BACH DANG · the Khan's fleet ──
  yuanScout: {
    kind: 'yuanScout',
    name: 'Mongol Scout Junk',
    faction: 'china',
    length: 56,
    width: 20,
    hp: 55,
    speed: 188,
    accel: 105,
    turn: 1.6,
    cannons: 2,
    reload: 2.2,
    damage: 7,
    range: 360,
    ballSpeed: 500,
    masts: 2,
    value: 250,
    coins: 9,
    crew: 40,
    hull: '#3a3430',
    deck: '#8a7a5a',
    trim: '#7a2d5a',
    sail: '#a8905a',
    sailShade: '#78643c',
    hullStyle: 'junk',
  },
  yuanFlagship: {
    kind: 'yuanFlagship',
    name: 'Mongol Invasion Flagship',
    faction: 'china',
    length: 104,
    width: 36,
    hp: 450,
    speed: 112,
    accel: 42,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 510,
    decks: 2,
    masts: 3,
    value: 1180,
    coins: 25,
    crew: 165,
    hull: '#2a2018',
    deck: '#5b3a22',
    trim: '#c9a227',
    sail: '#8a7448',
    sailShade: '#5c4c2e',
    hullStyle: 'junk',
    boss: true,
  },
  // ── LAKE TEXCOCO · brigantines and allies ──
  spanBrigantine: {
    kind: 'spanBrigantine',
    name: 'Spanish Brigantine',
    faction: 'spain',
    length: 52,
    width: 18,
    hp: 80,
    speed: 165,
    accel: 100,
    turn: 1.5,
    cannons: 2,
    reload: 2.3,
    damage: 8,
    range: 380,
    ballSpeed: 500,
    masts: 2,
    value: 280,
    coins: 10,
    crew: 40,
    hull: '#5a2e1c',
    deck: '#ab7742',
    trim: '#d4a72c',
    sail: '#f4ecd6',
    sailShade: '#cdbd96',
    oared: true,
  },
  tlaxCanoe: {
    kind: 'tlaxCanoe',
    name: 'Tlaxcalan War Canoe',
    faction: 'native',
    length: 54,
    width: 15,
    hp: 65,
    speed: 185,
    accel: 145,
    turn: 2.2,
    cannons: 2,
    reload: 2.2,
    damage: 6,
    range: 340,
    ballSpeed: 480,
    masts: 0,
    value: 230,
    coins: 9,
    crew: 42,
    hull: '#4a3a20',
    deck: '#7a5a34',
    trim: '#d4a72c',
    sail: '#9a7a44',
    sailShade: '#6b5230',
    hullStyle: 'canoe',
    oared: true,
  },
  supplyBrig: {
    kind: 'supplyBrig',
    name: 'Spanish Supply Brig',
    faction: 'spain',
    length: 54,
    width: 21,
    hp: 44,
    speed: 118,
    accel: 62,
    turn: 1.2,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 320,
    ballSpeed: 430,
    masts: 2,
    value: 140,
    coins: 12,
    crew: 22,
    hull: '#5c4326',
    deck: '#c39a62',
    trim: '#b3261e',
    sail: '#f7f0dc',
    sailShade: '#cdc09c',
    oared: true,
    trader: true,
    treasure: true,
  },
  cortesCapitana: {
    kind: 'cortesCapitana',
    name: "Cortés's Lake Capitana",
    faction: 'spain',
    length: 80,
    width: 26,
    hp: 390,
    speed: 140,
    accel: 70,
    turn: 1.2,
    cannons: 4,
    reload: 2.6,
    damage: 8,
    range: 420,
    ballSpeed: 510,
    masts: 2,
    value: 1100,
    coins: 22,
    crew: 110,
    hull: '#4a2418',
    deck: '#8f7048',
    trim: '#e8c14a',
    sail: '#f4ecd6',
    sailShade: '#cdbd96',
    oared: true,
    boss: true,
  },
};

export const UPGRADES: UpgradeDef[] = [
  { id: 'cannons', name: 'Extra Cannons', desc: '+1 gun on each broadside', max: 4 },
  { id: 'reload', name: 'Veteran Gun Crew', desc: 'Reload 15% faster', max: 5 },
  { id: 'damage', name: 'Heavy Shot', desc: '+25% cannonball damage', max: 5 },
  { id: 'hull', name: 'Oak Planking', desc: '+30 max hull & full repair', max: 5 },
  { id: 'sails', name: 'Silk Sails', desc: '+10% top speed', max: 4 },
  { id: 'rudder', name: 'Balanced Rudder', desc: '+18% turning speed', max: 3 },
  { id: 'range', name: 'Long Nines', desc: '+18% cannon range & velocity', max: 3 },
  { id: 'magnet', name: 'Greedy Parrot', desc: 'Grab loot from much further away', max: 3 },
  { id: 'carpenter', name: "Ship's Carpenter", desc: 'Repair 1.5 hull every second', max: 3 },
  { id: 'swivel', name: 'Swivel Guns', desc: 'Deck guns auto-fire at close foes', max: 3 },
  { id: 'chain', name: 'Chain Shot', desc: 'Your hits slow enemy ships', max: 1 },
  {
    id: 'grapeshot',
    name: 'Grape & Canister',
    desc: 'R: a point-blank blast all round — death to open boats',
    max: 3,
  },
  { id: 'chaser', name: 'Chase Guns', desc: 'Bow & stern guns fire on their own — rake your pursuers', max: 3 },
];

export function waveTitle(n: number): string {
  return waveTitleFor('golden', n);
}

export function waveTitleFor(era: EraId, n: number): string {
  const r = ERA_ROSTERS[era] ?? SAIL_ROSTER;
  if (n >= 1 && n <= 5) return r.titles[n - 1];
  if (n % 5 === 0) return r.bossTitle;
  return r.lines[n % r.lines.length];
}

export function waveComposition(n: number): ShipKind[] {
  return waveCompositionFor('golden', n);
}

export function waveCompositionFor(era: EraId, n: number): ShipKind[] {
  const r = ERA_ROSTERS[era] ?? SAIL_ROSTER;
  if (n >= 1 && n <= 5) return [...r.early[n - 1]];
  const list: ShipKind[] = [];
  if (n % 5 === 0) {
    const bosses = Math.min(3, Math.floor(n / 5));
    for (let i = 0; i < bosses; i++) list.push(r.boss);
    list.push(r.jackpot);
  }
  list.push(r.trader);
  let budget = 6 + (n - 5) * 1.7;
  const pool = r.pool.filter((p) => n >= (p.minWave ?? 0) && !(n % 5 === 0 && p.noBossWave));
  if (pool.length === 0) return list;
  const totalW = pool.reduce((a, p) => a + p.weight, 0);
  let guard = 0;
  while (budget > 0 && guard++ < 60) {
    let x = Math.random() * totalW;
    let pick = pool[0];
    for (const p of pool) {
      x -= p.weight;
      if (x <= 0) {
        pick = p;
        break;
      }
    }
    list.push(pick.kind);
    budget -= pick.cost;
  }
  return list;
}
