import type { ShipDef, ShipKind } from '../types';

/** Arabia: monsoon raiders of the Indian Ocean. */
export const ARABIA_DEFS = {
  // ── ARABIA · monsoon raiders ──
  warDhow: {
    kind: 'warDhow',
    name: 'Omani War Dhow',
    faction: 'arab',
    length: 64,
    width: 22,
    hp: 95,
    speed: 165,
    accel: 85,
    turn: 1.3,
    cannons: 3,
    reload: 2.3,
    damage: 8,
    range: 400,
    ballSpeed: 500,
    masts: 1,
    value: 280,
    coins: 10,
    crew: 45,
    hull: '#5c4326',
    deck: '#c39a62',
    trim: '#2e8a8a',
    sail: '#f0e6d0',
    sailShade: '#c0b090',
    hullStyle: 'dhow',
  },
  ghurab: {
    kind: 'ghurab',
    name: 'Qasimi Ghurab',
    faction: 'arab',
    length: 50,
    width: 17,
    hp: 42,
    speed: 198,
    accel: 115,
    turn: 1.8,
    cannons: 2,
    reload: 2.1,
    damage: 6,
    range: 360,
    ballSpeed: 500,
    masts: 1,
    value: 230,
    coins: 8,
    crew: 30,
    hull: '#4a3620',
    deck: '#a8824c',
    trim: '#c9403b',
    sail: '#f0e6d0',
    sailShade: '#c0b090',
    hullStyle: 'dhow',
  },
  baghlah: {
    kind: 'baghlah',
    name: 'Gulf Baghlah',
    faction: 'arab',
    length: 72,
    width: 28,
    hp: 120,
    speed: 125,
    accel: 55,
    turn: 1.0,
    cannons: 2,
    reload: 2.8,
    damage: 7,
    range: 360,
    ballSpeed: 480,
    masts: 2,
    value: 420,
    coins: 16,
    crew: 50,
    hull: '#6b4a2b',
    deck: '#c09a62',
    trim: '#2e5e8c',
    sail: '#efe3c4',
    sailShade: '#c3b48c',
    hullStyle: 'dhow',
    trader: true,
    treasure: true,
  },
  sultanFlagship: {
    kind: 'sultanFlagship',
    name: "Sultan's Flagship Ghanja",
    faction: 'arab',
    length: 100,
    width: 34,
    hp: 440,
    speed: 115,
    accel: 42,
    turn: 0.74,
    cannons: 5,
    reload: 3.0,
    damage: 7,
    range: 450,
    ballSpeed: 510,
    decks: 2,
    masts: 2,
    value: 1150,
    coins: 24,
    crew: 150,
    hull: '#3a2a4a',
    deck: '#8f7048',
    trim: '#c9a227',
    sail: '#f0e6d0',
    sailShade: '#c0b090',
    hullStyle: 'dhow',
    boss: true,
  },
  sambuk: {
    kind: 'sambuk',
    name: 'Red Sea Sambuk',
    faction: 'arab',
    length: 48,
    width: 16,
    hp: 40,
    speed: 192,
    accel: 112,
    turn: 1.75,
    cannons: 2,
    reload: 2.2,
    damage: 6,
    range: 350,
    ballSpeed: 490,
    masts: 1,
    value: 210,
    coins: 8,
    crew: 28,
    hull: '#5c4326',
    deck: '#c39a62',
    trim: '#c9403b',
    sail: '#f0e6d0',
    sailShade: '#c0b090',
    hullStyle: 'dhow',
  },
} satisfies Partial<Record<ShipKind, ShipDef>>;
