import type { ShipDef, ShipKind } from '../types';

/** Polynesia: the Māori Musket Wars and the Hawaiian Unification Wars. */
export const PACIFIC_DEFS = {
  // ── MĀORI · Musket Wars ──
  rivalWaka: {
    kind: 'rivalWaka',
    name: 'Rival Iwi Waka Taua',
    faction: 'maori',
    length: 56,
    width: 15,
    hp: 70,
    speed: 180,
    accel: 140,
    turn: 2.1,
    cannons: 2,
    reload: 2.2,
    damage: 6,
    range: 340,
    ballSpeed: 480,
    masts: 0,
    value: 240,
    coins: 10,
    crew: 45,
    hull: '#4a2e18',
    deck: '#7a5a34',
    trim: '#b5352c',
    sail: '#9a7a44',
    sailShade: '#6b5230',
    hullStyle: 'canoe',
    oared: true,
  },
  arikiWaka: {
    kind: 'arikiWaka',
    name: 'Ariki Great Waka',
    faction: 'maori',
    length: 84,
    width: 20,
    hp: 380,
    speed: 150,
    accel: 90,
    turn: 1.4,
    cannons: 4,
    reload: 2.6,
    damage: 7,
    range: 400,
    ballSpeed: 500,
    masts: 0,
    value: 1100,
    coins: 22,
    crew: 120,
    hull: '#3a2412',
    deck: '#6b4a28',
    trim: '#c9a227',
    sail: '#9a7a44',
    sailShade: '#6b5230',
    hullStyle: 'canoe',
    oared: true,
    boss: true,
  },
  flaxTrader: {
    kind: 'flaxTrader',
    name: 'Flax & Musket Trader',
    faction: 'merchant',
    length: 56,
    width: 22,
    hp: 42,
    speed: 115,
    accel: 60,
    turn: 1.2,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 320,
    ballSpeed: 430,
    masts: 2,
    value: 140,
    coins: 12,
    crew: 20,
    hull: '#5c4326',
    deck: '#c39a62',
    trim: '#3f7f6a',
    sail: '#f7f0dc',
    sailShade: '#cdc09c',
    trader: true,
    treasure: true,
  },
  // ── HAWAIʻI · Unification Wars ──
  rivalWaa: {
    kind: 'rivalWaa',
    name: 'Rival Moku Waʻa Kaua',
    faction: 'hawaii',
    length: 54,
    width: 15,
    hp: 68,
    speed: 185,
    accel: 145,
    turn: 2.2,
    cannons: 2,
    reload: 2.2,
    damage: 6,
    range: 340,
    ballSpeed: 480,
    masts: 0,
    value: 240,
    coins: 10,
    crew: 44,
    hull: '#5a3a20',
    deck: '#7a5a34',
    trim: '#c9a227',
    sail: '#a08050',
    sailShade: '#6f5836',
    hullStyle: 'canoe',
    oared: true,
  },
  kauaiFlagship: {
    kind: 'kauaiFlagship',
    name: 'Kauaʻi Royal Canoe Fleet',
    faction: 'hawaii',
    length: 82,
    width: 20,
    hp: 380,
    speed: 152,
    accel: 90,
    turn: 1.4,
    cannons: 4,
    reload: 2.6,
    damage: 7,
    range: 400,
    ballSpeed: 500,
    masts: 0,
    value: 1100,
    coins: 22,
    crew: 118,
    hull: '#4a2e16',
    deck: '#6b4a28',
    trim: '#b5352c',
    sail: '#a08050',
    sailShade: '#6f5836',
    hullStyle: 'canoe',
    oared: true,
    boss: true,
  },
  sandTrader: {
    kind: 'sandTrader',
    name: 'Sandalwood Trader',
    faction: 'merchant',
    length: 56,
    width: 22,
    hp: 42,
    speed: 115,
    accel: 60,
    turn: 1.2,
    cannons: 1,
    reload: 3.2,
    damage: 5,
    range: 320,
    ballSpeed: 430,
    masts: 2,
    value: 140,
    coins: 12,
    crew: 20,
    hull: '#5c4326',
    deck: '#c39a62',
    trim: '#8a5a2e',
    sail: '#f7f0dc',
    sailShade: '#cdc09c',
    trader: true,
    treasure: true,
  },
} satisfies Partial<Record<ShipKind, ShipDef>>;
