import type { ShipDef, ShipKind } from '../types';

// Somali piracy, 2005–2012: the Gulf of Aden and the Somali Basin. The
// pirates work from a mothership (a hijacked trawler or dhow) with fast
// fibreglass skiffs; their prey is the traffic of the Suez route; the navies
// of Combined Task Force 151 and EU NAVFOR Atalanta hunt them.

/** Hulls of the Gulf of Aden. */
export const SOMALI_DEFS = {
  bulkCarrier: {
    kind: 'bulkCarrier',
    name: 'Bulk Carrier',
    faction: 'merchant',
    length: 112,
    width: 26,
    hp: 210,
    speed: 100,
    accel: 40,
    turn: 0.75,
    cannons: 1, // a fire hose and a flare gun
    reload: 3.8,
    damage: 4,
    range: 300,
    ballSpeed: 460,
    masts: 0,
    crew: 22,
    value: 460,
    coins: 22,
    hull: '#8a2e26',
    deck: '#6e5a44',
    trim: '#e8e2d0',
    sail: '#8a2e26',
    sailShade: '#4e1a16',
    hullStyle: 'freighter',
    styleKey: 'bulkCarrier',
    trader: true,
  },
  containerShip: {
    kind: 'containerShip',
    name: 'Container Ship',
    faction: 'merchant',
    length: 140,
    width: 30,
    hp: 380,
    speed: 115,
    accel: 40,
    turn: 0.62,
    cannons: 1,
    reload: 3.6,
    damage: 5,
    range: 320,
    ballSpeed: 480,
    masts: 0,
    crew: 24,
    value: 1100,
    coins: 38,
    hull: '#1f3f66',
    deck: '#b8462e',
    trim: '#e8e2d0',
    sail: '#1f3f66',
    sailShade: '#122640',
    hullStyle: 'freighter',
    styleKey: 'containerShip',
    treasure: true,
  },
  rivalSkiff: {
    kind: 'rivalSkiff',
    name: 'Rival Clan Skiff',
    faction: 'pirate',
    length: 28,
    width: 9,
    hp: 26,
    speed: 245,
    accel: 170,
    turn: 2.6,
    cannons: 1,
    reload: 1.3,
    damage: 6,
    range: 330,
    ballSpeed: 640,
    projectile: 'missile', // an RPG-7 over the bow
    masts: 0,
    crew: 7,
    value: 120,
    coins: 5,
    hull: '#e8e2d0',
    deck: '#4189dd',
    trim: '#2a6fb8',
    sail: '#e8e2d0',
    sailShade: '#a8a290',
    hullStyle: 'warship',
    styleKey: 'rivalSkiff',
  },
  navRhib: {
    kind: 'navRhib',
    name: 'Navy Boarding RHIB',
    faction: 'england',
    length: 32,
    width: 10,
    hp: 38,
    speed: 250,
    accel: 160,
    turn: 2.4,
    cannons: 1,
    reload: 1.1,
    damage: 7,
    range: 380,
    ballSpeed: 720,
    masts: 0,
    crew: 10,
    value: 190,
    coins: 7,
    hull: '#2c2e30',
    deck: '#6a6e60',
    trim: '#e0a020',
    sail: '#2c2e30',
    sailShade: '#161718',
    hullStyle: 'warship',
    styleKey: 'navRhib',
  },
  pmpfBoat: {
    kind: 'pmpfBoat',
    name: 'Puntland Maritime Police Boat',
    faction: 'somalia',
    length: 44,
    width: 12,
    hp: 60,
    speed: 205,
    accel: 125,
    turn: 1.9,
    cannons: 2,
    reload: 1.5,
    damage: 7,
    range: 400,
    ballSpeed: 700,
    masts: 0,
    crew: 14,
    value: 240,
    coins: 8,
    hull: '#e4e2da',
    deck: '#7a8088',
    trim: '#4189dd',
    sail: '#e4e2da',
    sailShade: '#9a988e',
    hullStyle: 'warship',
    styleKey: 'pmpfBoat',
  },
  navFrigate: {
    kind: 'navFrigate',
    name: 'EU NAVFOR Frigate',
    faction: 'france',
    length: 88,
    width: 18,
    hp: 190,
    speed: 205,
    accel: 95,
    turn: 1.45,
    cannons: 3,
    reload: 1.5,
    damage: 11,
    range: 520,
    ballSpeed: 780,
    masts: 0,
    crew: 180,
    value: 560,
    coins: 15,
    hull: '#8a9094',
    deck: '#6a7074',
    trim: '#1f3f99',
    sail: '#8a9094',
    sailShade: '#4e5458',
    hullStyle: 'warship',
    styleKey: 'navFrigate',
  },
  bainbridge: {
    kind: 'bainbridge',
    name: 'USS Bainbridge (DDG-96)',
    boss: true,
    faction: 'usa',
    length: 120,
    width: 24,
    hp: 470,
    speed: 190,
    accel: 70,
    turn: 0.95,
    cannons: 5,
    reload: 2.0,
    damage: 12,
    range: 560,
    ballSpeed: 800,
    decks: 2,
    masts: 0,
    crew: 280,
    value: 1500,
    coins: 34,
    hull: '#7a8084',
    deck: '#5e6468',
    trim: '#2c3034',
    sail: '#7a8084',
    sailShade: '#44484c',
    hullStyle: 'warship',
    styleKey: 'bainbridge',
  },
} satisfies Partial<Record<ShipKind, ShipDef>>;
